<form enctype="multipart/form-data" method="post" action="<?= App::config('url') ?>Index/newPost">

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content" type="text">
        <input type="file" name="file" id="file">
    </div>

    <button type="submit">Save</button>
</form>



    <?php
    arsort($posts);

    foreach ($posts as $post):
        ?>
        <p><a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?>">

                <?php echo $post->getContent(); ?>   </a></p>
       <img src="../../images/<?= $post->getImage(); ?>">



            <p><?php echo date('d.m.Y H:i', strtotime($post->getTime()))?></p>
    <?php endforeach; ?>
