<form enctype="multipart/form-data" method="post" action="<?= App::config('url') ?>Index/newPost">

    <div class="container">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content" type="text">
        <input type="file" name="file" id="file">
        <button class="button-primary" type="submit">Save</button>
    </div>


</form>

<div class="column">
<?php
arsort($posts);

foreach ($posts as $post):
    ?>
    <p><a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?>">

            <?php echo $post->getContent(); ?>   </a></p>
    <?php if ($post->getImage()): ?>
    <img style="max-width: 600px" src="../../images/<?= $post->getImage(); ?>">

<?php endif; ?>
    <p> Comments (<?php echo $post->countComments($post->getId()); ?>)</p>


    <p><?php echo date('d.m.Y. H:i', strtotime($post->getTime())) ?></p>
<?php endforeach; ?>
</div>