<form enctype="multipart/form-data" method="post" action="<?= App::config('url') ?>Index/newPost">

    <div class="container">
        <h1 class="title">SOCIAL NETWORK</h1>

        <label for="content">What's on your mind?</label>
        <input class="u-full-width" id="content" name="content" type="text">
        <input type="file" name="file" id="file">
        <button class="button-primary" type="submit">Save</button>
    </div>


</form>

<div class="container">
    <?php
    arsort($posts);

    foreach ($posts as $post):
        ?>
        <h3><a style="text-decoration: none" href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?>">

                <?php echo $post->getContent(); ?>   </a></h3>
        <?php if ($post->getImage()): ?>
        <img style="max-width: 600px" src="../../images/<?= $post->getImage(); ?>">

    <?php endif; ?>
        <p> Comments (<?php echo $post->countComments($post->getId()); ?>)</p>


        <p><?php echo date('d.m.Y. H:i', strtotime($post->getTime())) ?></p>
    <?php endforeach; ?>
</div>