<div class="container">
    <h1><?= $post->getContent() ?></h1>
    <?php
    if ($post->getImage()):
        ?>
        <img style="max-width: 600px" src="../../images/<?= $post->getImage(); ?>">

    <?php endif; ?>

    <form method="post" action="<?= App::config('url') ?>Index/deletePost/<?= $post->getId() ?>">

        <button class="button-primary" type="submit">Delete Post</button>
    </form>
    <h3>Comments:<br/></h3>

    <?php


    foreach ($comments as $comment):
        ?>
        <p><?php echo $comment->getContent(); ?>   </p>

    <?php endforeach; ?>

    <form enctype="multipart/form-data" method="post"
          action="<?= App::config('url') ?>Index/newComment/<?= $post->getId() ?>">


        <label for="content">Anything you want to say?<br/></label>
        <input id="content" name="content" type="text">


        <button class="button-primary" type="submit">Comment</button>
    </form>
</div>